### PR TITLE
Fix unit tests and set up Travis and Coveralls

### LINKED ISSUE #1: Add setup.py and make elasticstart into a package

### PR DESCRIPTION
**Pull request by alvaromorales**
Fixes #1 #2

### CODE REVIEW

**Comment by michaelsilver** [comment]
My only inclination is to have `python setup.py install` in your `install:` steps, like I have in WikiMap, because it is the same way someone would install your package, so it seems the best way to assure everything works as expected:
```yml
language: python
python:
- '2.7'
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/nltk_data
install:
- pip install coveralls
- python setup.py install
- python -c "import nltk; nltk.download('punkt'); nltk.download('wordnet'); nltk.download('stopwords');"
script:
- coverage run setup.py test
after_success:
- coveralls
env:
  global:
(...)
```

Also, what does the caching do and why did you chose to include caching on those things?

Otherwise, looks good.

**Comment by alvaromorales** [comment]
Thanks, I updated `setup.py`.

Travis builds a project in a container -- think of it as a fresh, blank machine every time. The bulk of the build time is spent installing pip packages and nltk modules. To save time, Travis can cache those (zip file and upload to S3), and on the next build just pull down the zip file. Build times are much faster!

Usually, all you have to do is add `cache: pip`, but because of nltk_data I went for the arbitrary directory caching method.

**Comment by alvaromorales** [comment]
Also, I'm not sure if I set up coveralls correctly. Could you take a look at the coverage report?

**Comment by michaelsilver** [comment]
Looks fine to me; the only thing is I would suggest adding `tests` to your packages in your `setup.py`. I think you are supposed to do that anyways, and also it appears on the coverage report so that you can be assured all tests are run by nose (if you have a typo, such as `tes_` instead of `test_`, it won't run, so seeing that in coveralls is nice to know). Also, you should get rid of the `requirements.txt` file. This may be a little nit-pickly, but have you considered adding `elasticstart_server.py` into the `elasticstart` package and having an `entry_point` call it?

About caching: I'm not sure how much of an improvement in speed it gives you over the potential problems it can cause. Suppose one of your dependancies updates and changes some important functionality (they made a mistake they shouldn't have made), better you see that mistake because Travis installs everythign fresh than only find out by accident when someone else tries to install your module. Plus, by choosing to download only individual parts of nltk, it is very very small, so no real need to cache that, I don't think.

**Comment by alvaromorales** [comment]
Merging because suggestions are outside of the scope of this PR.

requirements.txt is a python convention -- see [this link](https://pip.readthedocs.org/en/1.1/requirements.html). Whenever you have a question about python packaging, look at [requests](https://github.com/kennethreitz/requests).

`packages` should contain exportable packages -- `tests` is not one of them.

> Suppose one of your dependancies updates and changes some important functionality (they made a mistake they shouldn't have made)

I'm freezing the version of packages in requirements.txt, to avoid auto-upgrading to new versions of packages that might have breaking changes. Dependencies are guaranteed to stay the same across builds, thus caching.

**Comment by michaelsilver** [comment]
> I'm freezing the version of packages in requirements.txt, to avoid auto-upgrading to new versions of packages that might have breaking changes. Dependencies are guaranteed to stay the same across builds, thus caching.

Yes, but you are not freezing the versions of your dependencies in the `setup.py`, which means that although you have frozen them in the `requirements.txt`, it is the `setup.py` which is used for installation, and setuptools will install any version of the dependencies (but Travis will behave *as if* you have frozen the dependencies, only because you cached them). If you want to actually freeze your dependencies, put version numbers in the `setup.py`:
```Python
    install_requires=[
        'defexpand',
        'elasticsearch==1.3.0',
        'jsonrpclib==0.1.3',
        'pyparsing==2.0.3',
        'requests==2.5.1',
        'xmltodict==0.9.0',
    ],
```
Once you do that, I really puzzle over the reason to keep a `requirements.txt` file around. See [flask](https://github.com/mitsuhiko/flask) and [django](https://github.com/django/django). 

About whether to include tests, I do agree it is not so clear...

**Comment by alvaromorales** [comment]
Thanks for pointing out that the requirements file isn't being read. I've opened a PR to make Travis install dependencies from requirements.txt.

This is starting to get into the territory of opinionated packaging; the answers below apply to elasticstart.

- `requirements.txt` contains script dependencies, such as paramiko, that are required to run scripts but are not necessary to install the main elasticstart package.
- `tests` should not be in the list of packages, because they are not exportable. No other script should be able to run `from elasticstart import tests`.

Freezing versions in `setup.py` signals that the package 'only works' with the pinned dependency. I like the distinction between abstract and concrete dependencies, and need a way of specifying a set of dependencies where things 'have worked'. Thus, requirements.txt.

My main priority is to have all elasticstart collaborators work in the same environment and ensure repeatable installations.

**Comment by michaelsilver** [comment]
Ah... makes sense now that you explained your reasoning. I totally agree nobody should be able to run `from elasticstart import tests`. I'm going to fix this in infolab-csail/wikimap#8. Glad we're on the same page about `requirements.txt` previously not running. I will take a look at #6.

**Comment by michaelsilver** [comment]
Also, thanks for explaining about abstract vs. concrete dependencies! Once nice thing about talking out a code review is that I learned something in the process. :+1:

**Pull request merged**
