### PR TITLE
Import defexpand as a python module

### PR DESCRIPTION
**Pull request by michaelsilver**
This should do it. Let me know if I need to fix anything up. 

The only thing that concerns me is that `defexpand` uses something from `elasticstart`, so `defexpand` imports `elasticstart`, and `elasticstart` imports `defexpand`, creating a circular dependency problem. How do you think this could best be solved?

### CODE REVIEW

**Comment by alvaromorales** [comment]
Thanks for setting this up, it's a great idea. Have you tested it to make sure the imports work correctly?

defexpand should not depend on elasticstart. You should just move `defexpand/scripts/get_inf_to_def.py` into `elasticstart/scripts` -- it's the only occurrence. Circular dependencies create a lot of issues.

**Comment by michaelsilver** [comment]
I just moved that file and removed the circular dependency. In terms of testing, I was half way through setting up Travis before I had to run (for some reason Travis is on, but there is no yml file so that's why it's failing). If you have the chance feel free to set it up, otherwise I'll try to get to it tonight. 

Michael

**Comment by michaelsilver** [comment]
So I went through and crated a `setup.py` with all the deps, and set up Travis. I just used the sample `conifg.py`, but obviously we're getting errors (that may or may not be related). @alvaromorales, could you push a "good" `config.py` so we can start isolating the problems?

**Comment by alvaromorales** [comment]
@michaelsilver thanks for beginning to set up Travis. When I asked if you had tested your PR, I just wanted to know if you were able to correctly import `defexpand`, not necessarily pass tests.

I can't upload the real config.py because it contains various passwords. I need to figure out Travis encryption keys. I believe some tests are broken from last semester, so there is still some work left to do. I'll open issues for them and keep you updated.

I was ready to merge this before before your latest commit. Can you revert `9a15ac7`? For future reference, please try to keep PRs limited to a single thing -- in this case, moving defexpand to a separate repo. (Of course, this guideline may not always work, as some issues may require big changes all over the place).

**Comment by michaelsilver** [comment]
Sorry, when you said "test", I assumed you meant the unittests (which should, if they pass, indicate that I didn't mess up anything -- that's why I went down the path of Travis, esp. given that I saw Travis was turned on...) Anyways, unless I made some typo (I triple checked) the imports should be working. At least, importing defexpand seems to work both in wikithingsdb and wikimap, which is why I moved it into a separate repo in the first place.

@alvaromorales, I just reverted to 9a15ac7.

**Comment by alvaromorales** [comment]
Thanks, @michaelsilver! I'll work on getting unit tests to pass asap. I updated Travis to only build if a .travis.yml file is present.

**Pull request merged**
